<?php

use Illuminate\Database\Seeder;

class MapelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
			DB::table('mata_pelajarans')->insert([
				[
					'nama' => 'Pendidikan Agama dan Budi Pekerti',
					'keterangan'=>'Islam',
					'jenis'=>1,
					'urutan'=>1,
					'kelas_id'=>1,
					'kelompok_id'=>1,
				],[
					'nama' => 'Pendidikan Agama dan Budi Pekerti',
					'keterangan'=>'Kristen',
					'jenis'=>1,
					'urutan'=>1,
					'kelas_id'=>1,
					'kelompok_id'=>1,
				],[
					'nama' => 'Pendidikan Agama dan Budi Pekerti',
					'keterangan'=>'Katolik',
					'jenis'=>1,
					'urutan'=>1,
					'kelas_id'=>1,
					'kelompok_id'=>1,
				],[
					'nama' => 'Pendidikan Agama dan Budi Pekerti',
					'keterangan'=>'Hindu',
					'jenis'=>1,
					'urutan'=>1,
					'kelas_id'=>1,
					'kelompok_id'=>1,
				],[
					'nama' => 'Pendidikan Agama dan Budi Pekerti',
					'keterangan'=>'Budha',
					'jenis'=>1,
					'urutan'=>1,
					'kelas_id'=>1,
					'kelompok_id'=>1,
				],[
					'nama' => 'Pendidikan Agama dan Budi Pekerti',
					'keterangan'=>'Konghucu',
					'jenis'=>1,
					'urutan'=>1,
					'kelas_id'=>1,
					'kelompok_id'=>1,
				],[
					'nama' => 'Pendidikan Agama dan Budi Pekerti',
					'keterangan'=>'Islam',
					'jenis'=>1,
					'urutan'=>1,
					'kelas_id'=>2,
					'kelompok_id'=>1,
				],[
					'nama' => 'Pendidikan Agama dan Budi Pekerti',
					'keterangan'=>'Kristen',
					'jenis'=>1,
					'urutan'=>1,
					'kelas_id'=>2,
					'kelompok_id'=>1,
				],[
					'nama' => 'Pendidikan Agama dan Budi Pekerti',
					'keterangan'=>'Katolik',
					'jenis'=>1,
					'urutan'=>1,
					'kelas_id'=>2,
					'kelompok_id'=>1,
				],[
					'nama' => 'Pendidikan Agama dan Budi Pekerti',
					'keterangan'=>'Hindu',
					'jenis'=>1,
					'urutan'=>1,
					'kelas_id'=>2,
					'kelompok_id'=>1,
				],[
					'nama' => 'Pendidikan Agama dan Budi Pekerti',
					'keterangan'=>'Budha',
					'jenis'=>1,
					'urutan'=>1,
					'kelas_id'=>2,
					'kelompok_id'=>1,
				],[
					'nama' => 'Pendidikan Agama dan Budi Pekerti',
					'keterangan'=>'Konghucu',
					'jenis'=>1,
					'urutan'=>1,
					'kelas_id'=>2,
					'kelompok_id'=>1,
				],[
					'nama' => 'Pendidikan Agama dan Budi Pekerti',
					'keterangan'=>'Islam',
					'jenis'=>1,
					'urutan'=>1,
					'kelas_id'=>3,
					'kelompok_id'=>1,
				],[
					'nama' => 'Pendidikan Agama dan Budi Pekerti',
					'keterangan'=>'Kristen',
					'jenis'=>1,
					'urutan'=>1,
					'kelas_id'=>3,
					'kelompok_id'=>1,
				],[
					'nama' => 'Pendidikan Agama dan Budi Pekerti',
					'keterangan'=>'Katolik',
					'jenis'=>1,
					'urutan'=>1,
					'kelas_id'=>3,
					'kelompok_id'=>1,
				],[
					'nama' => 'Pendidikan Agama dan Budi Pekerti',
					'keterangan'=>'Hindu',
					'jenis'=>1,
					'urutan'=>1,
					'kelas_id'=>3,
					'kelompok_id'=>1,
				],[
					'nama' => 'Pendidikan Agama dan Budi Pekerti',
					'keterangan'=>'Budha',
					'jenis'=>1,
					'urutan'=>1,
					'kelas_id'=>3,
					'kelompok_id'=>1,
				],[
					'nama' => 'Pendidikan Agama dan Budi Pekerti',
					'keterangan'=>'Konghucu',
					'jenis'=>1,
					'urutan'=>1,
					'kelas_id'=>3,
					'kelompok_id'=>1,
				],[
					'nama' => 'Pendidikan Pancasila dan Kewarganegaraan',
					'keterangan'=>'',
					'jenis'=>0,
					'urutan'=>2,
					'kelas_id'=>1,
					'kelompok_id'=>1,
				],[
					'nama' => 'Pendidikan Pancasila dan Kewarganegaraan',
					'keterangan'=>'',
					'jenis'=>0,
					'urutan'=>2,
					'kelas_id'=>2,
					'kelompok_id'=>1,
				],[
					'nama' => 'Pendidikan Pancasila dan Kewarganegaraan',
					'keterangan'=>'',
					'jenis'=>0,
					'urutan'=>2,
					'kelas_id'=>3,
					'kelompok_id'=>1,
				],[
					'nama' => 'Bahasa Indonesia',
					'keterangan'=>'',
					'jenis'=>0,
					'urutan'=>3,
					'kelas_id'=>1,
					'kelompok_id'=>1,
				],[
					'nama' => 'Bahasa Indonesia',
					'keterangan'=>'',
					'jenis'=>0,
					'urutan'=>3,
					'kelas_id'=>2,
					'kelompok_id'=>1,
				],[
					'nama' => 'Bahasa Indonesia',
					'keterangan'=>'',
					'jenis'=>0,
					'urutan'=>3,
					'kelas_id'=>3,
					'kelompok_id'=>1,
				],[
					'nama' => 'Matematika',
					'keterangan'=>'',
					'jenis'=>0,
					'urutan'=>4,
					'kelas_id'=>1,
					'kelompok_id'=>1,
				],[
					'nama' => 'Matematika',
					'keterangan'=>'',
					'jenis'=>0,
					'urutan'=>4,
					'kelas_id'=>2,
					'kelompok_id'=>1,
				],[
					'nama' => 'Matematika',
					'keterangan'=>'',
					'jenis'=>0,
					'urutan'=>4,
					'kelas_id'=>3,
					'kelompok_id'=>1,
				],[
					'nama' => 'Biologi',
					'keterangan'=>'',
					'jenis'=>0,
					'urutan'=>5,
					'kelas_id'=>1,
					'kelompok_id'=>1,
				],[
					'nama' => 'Biologi',
					'keterangan'=>'',
					'jenis'=>0,
					'urutan'=>5,
					'kelas_id'=>2,
					'kelompok_id'=>1,
				],[
					'nama' => 'Biologi',
					'keterangan'=>'',
					'jenis'=>0,
					'urutan'=>5,
					'kelas_id'=>3,
					'kelompok_id'=>1,
				],[
					'nama' => 'Fisika',
					'keterangan'=>'',
					'jenis'=>0,
					'urutan'=>6,
					'kelas_id'=>1,
					'kelompok_id'=>1,
				],[
					'nama' => 'Fisika',
					'keterangan'=>'',
					'jenis'=>0,
					'urutan'=>6,
					'kelas_id'=>2,
					'kelompok_id'=>1,
				],[
					'nama' => 'Fisika',
					'keterangan'=>'',
					'jenis'=>0,
					'urutan'=>6,
					'kelas_id'=>3,
					'kelompok_id'=>1,
				],[
					'nama' => 'Kimia',
					'keterangan'=>'',
					'jenis'=>0,
					'urutan'=>7,
					'kelas_id'=>1,
					'kelompok_id'=>1,
				],[
					'nama' => 'Kimia',
					'keterangan'=>'',
					'jenis'=>0,
					'urutan'=>7,
					'kelas_id'=>2,
					'kelompok_id'=>1,
				],[
					'nama' => 'Kimia',
					'keterangan'=>'',
					'jenis'=>0,
					'urutan'=>7,
					'kelas_id'=>3,
					'kelompok_id'=>1,
				],[
					'nama' => 'Ilmu Pengetahuan Sosial',
					'keterangan'=>'',
					'jenis'=>0,
					'urutan'=>8,
					'kelas_id'=>1,
					'kelompok_id'=>1,
				],[
					'nama' => 'Ilmu Pengetahuan Sosial',
					'keterangan'=>'',
					'jenis'=>0,
					'urutan'=>8,
					'kelas_id'=>2,
					'kelompok_id'=>1,
				],[
					'nama' => 'Ilmu Pengetahuan Sosial',
					'keterangan'=>'',
					'jenis'=>0,
					'urutan'=>8,
					'kelas_id'=>3,
					'kelompok_id'=>1,
				],[
					'nama' => 'Bahasa Inggris',
					'keterangan'=>'',
					'jenis'=>0,
					'urutan'=>9,
					'kelas_id'=>1,
					'kelompok_id'=>1,
				],[
					'nama' => 'Bahasa Inggris',
					'keterangan'=>'',
					'jenis'=>0,
					'urutan'=>9,
					'kelas_id'=>2,
					'kelompok_id'=>1,
				],[
					'nama' => 'Bahasa Inggris',
					'keterangan'=>'',
					'jenis'=>0,
					'urutan'=>9,
					'kelas_id'=>3,
					'kelompok_id'=>1,
				],[
					'nama' => 'Seni Budaya',
					'keterangan'=>'Seni Rupa',
					'jenis'=>0,
					'urutan'=>1,
					'kelas_id'=>1,
					'kelompok_id'=>2,
				],[
					'nama' => 'Seni Budaya',
					'keterangan'=>'Seni Rupa',
					'jenis'=>0,
					'urutan'=>1,
					'kelas_id'=>2,
					'kelompok_id'=>2,
				],[
					'nama' => 'Seni Budaya',
					'keterangan'=>'Seni Rupa',
					'jenis'=>0,
					'urutan'=>1,
					'kelas_id'=>3,
					'kelompok_id'=>2,
				],[
					'nama' => 'Seni Budaya',
					'keterangan'=>'Seni Musik',
					'jenis'=>0,
					'urutan'=>2,
					'kelas_id'=>1,
					'kelompok_id'=>2,
				],[
					'nama' => 'Seni Budaya',
					'keterangan'=>'Seni Musik',
					'jenis'=>0,
					'urutan'=>2,
					'kelas_id'=>2,
					'kelompok_id'=>2,
				],[
					'nama' => 'Seni Budaya',
					'keterangan'=>'Seni Musik',
					'jenis'=>0,
					'urutan'=>2,
					'kelas_id'=>3,
					'kelompok_id'=>2,
				],[
					'nama' => 'Pendidikan Jasmani, Olahraga, dan Kesahatan',
					'keterangan'=>'',
					'jenis'=>0,
					'urutan'=>3,
					'kelas_id'=>1,
					'kelompok_id'=>2,
				],[
					'nama' => 'Pendidikan Jasmani, Olahraga, dan Kesahatan',
					'keterangan'=>'',
					'jenis'=>0,
					'urutan'=>3,
					'kelas_id'=>2,
					'kelompok_id'=>2,
				],[
					'nama' => 'Pendidikan Jasmani, Olahraga, dan Kesahatan',
					'keterangan'=>'',
					'jenis'=>0,
					'urutan'=>3,
					'kelas_id'=>3,
					'kelompok_id'=>2,
				],[
					'nama' => 'Prakarya',
					'keterangan'=>'Kerajinan',
					'jenis'=>0,
					'urutan'=>4,
					'kelas_id'=>1,
					'kelompok_id'=>2,
				],[
					'nama' => 'Prakarya',
					'keterangan'=>'Kerajinan',
					'jenis'=>0,
					'urutan'=>4,
					'kelas_id'=>2,
					'kelompok_id'=>2,
				],[
					'nama' => 'Prakarya',
					'keterangan'=>'Kerajinan',
					'jenis'=>0,
					'urutan'=>4,
					'kelas_id'=>3,
					'kelompok_id'=>2,
				],[
					'nama' => 'Bahasa Jawa',
					'keterangan'=>'',
					'jenis'=>0,
					'urutan'=>5,
					'kelas_id'=>1,
					'kelompok_id'=>2,
				],[
					'nama' => 'Bahasa Jawa',
					'keterangan'=>'',
					'jenis'=>0,
					'urutan'=>5,
					'kelas_id'=>2,
					'kelompok_id'=>2,
				],[
					'nama' => 'Bahasa Jawa',
					'keterangan'=>'',
					'jenis'=>0,
					'urutan'=>5,
					'kelas_id'=>3,
					'kelompok_id'=>2,
				]
			]);
    }
}
